In [31]:
import numpy as np


In [32]:
x_train_path = "../data/x_train.txt"
y_train_path = "../data/y_train.txt"

x_data = np.loadtxt(x_train_path, delimiter=' ')
y_data = np.loadtxt(y_train_path, delimiter=' ')

print("X shape:", x_data.shape)
print("Y shape:", y_data.shape)


X shape: (5000, 500)
Y shape: (5000,)


In [33]:
print(x_data)


[[-2.61977304 -2.61953328 -1.19935019 ... 16.24390748  7.20952428
   8.08202144]
 [-1.41557893 -1.78254367 -2.88027041 ... 12.18767008 12.28386068
   5.0322849 ]
 [-2.74509151 -1.38294477 -1.62601519 ... 11.9393541  11.65361994
   5.94277822]
 ...
 [-0.41899368 -3.16423075 -1.05778919 ...  7.26452027 11.03634131
  11.27432363]
 [ 2.29101486  1.07369718  0.07184925 ... 10.09009627 19.41599069
   9.16393405]
 [-0.50491196 -0.72755641 -0.33166452 ...  7.89974476  9.80064955
  11.19871414]]


In [34]:
from sklearn.preprocessing import MinMaxScaler

standard_scaler = MinMaxScaler(feature_range=(0, 1))
x_data_standardized = standard_scaler.fit_transform(x_data, y_data)

print(x_data_standardized)


[[0.31899799 0.36861539 0.45248708 ... 0.50336432 0.18728825 0.23677527]
 [0.4019942  0.42281264 0.33283508 ... 0.36700072 0.34992154 0.14059724]
 [0.31036071 0.44868771 0.42211602 ... 0.35865277 0.32972223 0.16931101]
 ...
 [0.47068146 0.33334481 0.46256374 ... 0.20149303 0.30993835 0.33744933]
 [0.65746235 0.60776165 0.54297416 ... 0.29648395 0.57850745 0.27089501]
 [0.46475975 0.4911258  0.51425106 ... 0.22284817 0.27033423 0.33506487]]


In [35]:
# from sklearn.preprocessing import Normalizer

# normalizer = Normalizer(norm="l2")

# x_df_normalized = normalizer.fit_transform(x_data)

# print(x_df_normalized)


In [36]:
from sklearn.preprocessing import PolynomialFeatures

polunomial_builder = PolynomialFeatures()
x_df_poly = polunomial_builder.fit_transform(x_data_standardized)

print("X polynomialed shape:", x_df_poly.shape)


X polynomialed shape: (5000, 125751)


In [37]:
np.int = np.int32
np.float = np.float64
np.bool = np.bool_

from boruta import BorutaPy


In [38]:
from sklearn.ensemble import RandomForestClassifier

feature_names = [f"feature {i}" for i in range(x_df_poly.shape[1])]
forest = RandomForestClassifier(random_state=0)
forest.fit(x_df_poly, y_data)
feature_importances = forest.feature_importances_

forest_importances = {
    feature_names[i]: feature_importances[i]
    for i in range(len(feature_names))
}

sorted_features = sorted(
    forest_importances.items(),
    key=lambda x:x[1],
    reverse=True
)

the_best_features = sorted_features[:10]

top_indices = [feature_names.index(feature) for feature, importance in the_best_features]
top_columns = x_df_poly[:, top_indices]

print(top_columns)


[[0.22612814 0.12426396 0.18488481 ... 0.23496505 0.35251094 0.23645879]
 [0.09255822 0.0755147  0.17568017 ... 0.35322417 0.27479938 0.1424122 ]
 [0.12965368 0.09826972 0.1453864  ... 0.31249087 0.31348002 0.18557486]
 ...
 [0.29576921 0.27578278 0.35543815 ... 0.14704091 0.52515025 0.18774271]
 [0.33447473 0.27488224 0.23762021 ... 0.39840596 0.52429213 0.38772452]
 [0.1370363  0.2671744  0.29193861 ... 0.24860481 0.51688915 0.13020599]]


In [39]:
# TAKES TOO MUCH TIME

# from sklearn.ensemble import RandomForestClassifier

# rf = RandomForestClassifier(n_jobs=-1, class_weight="balanced")
# boruta_model = BorutaPy(rf, n_estimators="auto")
# boruta_model.fit(x_df_poly, y_data)

# feature_names = [f"feature {i}" for i in range(x.shape[1])]
# feature_importances = boruta_model.support_

# the_best_features = [
#     (feature_names[i], 1.0)
#     for i in range(len(feature_names))
#     if feature_importances[i] == True
# ]

# print(len(the_best_features))


In [42]:
with open("the_best_features.txt", "w") as file:
    for feature in the_best_features:
        print(feature[0], file=file)
